spring.application.name=repair
spring.datasource.url=jdbc:postgresql://localhost:5432/repair
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=apple
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.docker.compose.enabled=false
